### ISSUE TITLE
Для присвоения к полям экземпляра нужно использовать this

### ISSUE THREAD

**Issue by Bratchvv** [aleksan7772/Laba6#2]
https://github.com/aleksan7772/Laba6/blob/158f9a1a21fa04fc3e578b6d0fe8e2f955b1ec28/src/Book.java#L13

this.name = name.
А еще лучше использовать генератор сеттеров/геттеров в IDEA. (alt+insert)

**Comment by aleksan7772** [comment]
public class Book {
    public static int numberPages;
    private String name;
    private int[] numberOfPages = new int[50];
    private String[] chapterList = new String[5];
    private String category;
    private Boolean palette;

    {
        chapterList[0] = "Введение";
        chapterList[1] = "Основы военного дела";
        chapterList[2] = "Военные стратегии";
        chapterList[3] = "Виды боевых машин";
        chapterList[4] = "Сражение на воде";

    }

    public static int getNumberPages() {
        return numberPages;
    }

    public static void setNumberPages(int numberPages) {
        Book.numberPages = numberPages;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int[] getNumberOfPages() {
        return numberOfPages;
    }

    public void setNumberOfPages(int[] numberOfPages) {
        this.numberOfPages = numberOfPages;
    }

    public String[] getChapterList() {
        return chapterList;
    }

    public void setChapterList(String[] chapterList) {
        this.chapterList = chapterList;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Boolean getPalette() {
        return palette;
    }

    public void setPalette(Boolean palette) {
        this.palette = palette;
    }
}

**Comment by aleksan7772** [comment]
я не пойму как вы так красиво вставляете код?
